import type { Asset, RunRecord, StepState, VideoOptions } from "./types"
import { buildPipeline, logsFor } from "./steps"
import { buildScenes } from "./editor"
import { saveRun, getRun } from "./store"
import {
  appHost,
  fetchRepoMeta,
  hasB2,
  hasEleven,
  hasGmi,
  parseRepo,
  shortHash,
  synthesizeVoice,
  uploadToB2,
  writeScript,
} from "./integrations"

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

export function createRun(id: string, repoUrl: string, appUrl: string, options: VideoOptions): RunRecord {
  const steps: StepState[] = buildPipeline({ presenter: options.presenter.enabled }).map((d) => ({
    id: d.id,
    status: "pending",
    logs: [],
    mode: "simulated",
  }))
  const run: RunRecord = {
    id,
    repoUrl,
    appUrl,
    createdAt: Date.now(),
    status: "running",
    steps,
    options,
  }
  saveRun(run)
  return run
}

function modeForStep(stepId: string): "real" | "simulated" {
  if (stepId === "ingest") return "real" // GitHub public API always attempted
  if (stepId === "analyze" || stepId === "script") return hasGmi() ? "real" : "simulated"
  if (stepId === "voiceover") return hasEleven() ? "real" : "simulated"
  if (stepId === "publish") return hasB2() ? "real" : "simulated"
  return "simulated"
}

export async function runPipeline(id: string) {
  const run = getRun(id)
  if (!run) return

  const opts = run.options
  const { full } = parseRepo(run.repoUrl)
  const host = appHost(run.appUrl)
  const logMap = logsFor(full, host, {
    format: opts.format,
    durationSec: opts.maxDurationSec,
    presenterName: opts.presenter.name,
  })
  const pipeline = buildPipeline({ presenter: opts.presenter.enabled })

  let scriptText = ""
  let meta = await fetchRepoMeta(run.repoUrl).catch(() => null)

  for (let i = 0; i < pipeline.length; i++) {
    const def = pipeline[i]
    const cur = getRun(id)
    if (!cur) return
    const step = cur.steps[i]
    step.status = "active"
    step.startedAt = Date.now()
    step.mode = modeForStep(def.id)
    saveRun(cur)

    const lines = logMap[def.id] ?? []
    const per = Math.max(400, Math.floor(def.duration / Math.max(lines.length, 1)))

    // Kick off real side-effects for certain steps while logs stream.
    let sideEffect: Promise<unknown> | null = null
    if (def.id === "script") {
      sideEffect = writeScript(
        meta ?? {
          full,
          description: "A modern web application.",
          language: "TypeScript",
          stars: 0,
          topics: [],
          readmeExcerpt: "",
        },
        run.appUrl,
        { format: opts.format, durationSec: opts.maxDurationSec, presenterName: opts.presenter.name },
      ).then((t) => {
        scriptText = t
      })
    } else if (def.id === "voiceover") {
      sideEffect = synthesizeVoice(scriptText || "Devfields demo narration.")
    }

    for (const line of lines) {
      await sleep(per)
      const c = getRun(id)
      if (!c) return
      c.steps[i].logs.push(line)
      saveRun(c)
    }

    if (sideEffect) await sideEffect.catch(() => {})

    const done = getRun(id)
    if (!done) return
    done.steps[i].status = "done"
    done.steps[i].finishedAt = Date.now()
    saveRun(done)
  }

  // Build result + provenance assets
  const finalRun = getRun(id)
  if (!finalRun) return

  if (!scriptText) {
    scriptText = `Meet ${full.split("/")[1]} — an automated demo generated by Devfields.`
  }

  const assetSpecs: { key: string; label: string; kind: Asset["kind"]; size: string; provider: Asset["provider"]; seed: string }[] = [
    { key: `runs/${id}/manifest.json`, label: "Provenance manifest", kind: "json", size: "3.1 KB", provider: "Backblaze B2", seed: full + id },
    { key: `runs/${id}/script.json`, label: "Narration script", kind: "text", size: "2.4 KB", provider: "GMI Cloud", seed: scriptText },
    { key: `runs/${id}/voiceover.mp3`, label: "Voiceover audio", kind: "audio", size: "1.2 MB", provider: "ElevenLabs", seed: "audio" + id },
    { key: `runs/${id}/frames.zip`, label: "Captured frames", kind: "image", size: "8.7 MB", provider: "Devfields", seed: "frames" + id },
  ]
  if (opts.presenter.enabled) {
    assetSpecs.push({ key: `runs/${id}/presenter.mp4`, label: "Presenter avatar clip", kind: "video", size: "6.4 MB", provider: "Devfields", seed: "presenter" + id })
  }
  assetSpecs.push({ key: `runs/${id}/demo.mp4`, label: "Final demo video", kind: "video", size: "24.3 MB", provider: "Devfields", seed: "video" + id })

  const assets: Asset[] = []
  for (const s of assetSpecs) {
    const { b2Key } = await uploadToB2(s.key, s.seed)
    const hash = await shortHash(s.seed)
    assets.push({
      key: s.key,
      label: s.label,
      kind: s.kind,
      size: s.size,
      b2Key,
      hash,
      provider: s.provider,
    })
  }

  const durationSec = opts.maxDurationSec
  finalRun.result = {
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    posterUrl: `/demo-poster.png`,
    durationSec,
    title: `${full.split("/")[1]} — ${opts.format === "pitch_demo" ? "Pitch + Demo" : "Demo"}`,
    summary: meta?.description ?? "An automated demo of your deployed application.",
    scriptPreview: scriptText,
    assets,
    scenes: buildScenes(scriptText, durationSec, opts.format),
    version: 1,
    edits: [],
    format: opts.format,
    presenter: opts.presenter.enabled ? opts.presenter : undefined,
  }
  finalRun.status = "done"
  saveRun(finalRun)
}
