import type { Asset, RunRecord, StepState } from "./types"
import { STEP_DEFS, logsFor } from "./steps"
import { saveRun, getRun } from "./store"
import {
  appHost,
  fetchRepoMeta,
  hasB2,
  hasEleven,
  hasGmi,
  parseRepo,
  shortHash,
  synthesizeVoice,
  uploadToB2,
  writeScript,
} from "./integrations"

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

export function createRun(id: string, repoUrl: string, appUrl: string): RunRecord {
  const steps: StepState[] = STEP_DEFS.map((d) => ({
    id: d.id,
    status: "pending",
    logs: [],
    mode: "simulated",
  }))
  const run: RunRecord = {
    id,
    repoUrl,
    appUrl,
    createdAt: Date.now(),
    status: "running",
    steps,
  }
  saveRun(run)
  return run
}

function modeForStep(stepId: string): "real" | "simulated" {
  if (stepId === "ingest") return "real" // GitHub public API always attempted
  if (stepId === "analyze" || stepId === "script") return hasGmi() ? "real" : "simulated"
  if (stepId === "voiceover") return hasEleven() ? "real" : "simulated"
  if (stepId === "publish") return hasB2() ? "real" : "simulated"
  return "simulated"
}

export async function runPipeline(id: string) {
  const run = getRun(id)
  if (!run) return

  const { full } = parseRepo(run.repoUrl)
  const host = appHost(run.appUrl)
  const logMap = logsFor(full, host)

  let scriptText = ""
  let meta = await fetchRepoMeta(run.repoUrl).catch(() => null)

  for (let i = 0; i < STEP_DEFS.length; i++) {
    const def = STEP_DEFS[i]
    const cur = getRun(id)
    if (!cur) return
    const step = cur.steps[i]
    step.status = "active"
    step.startedAt = Date.now()
    step.mode = modeForStep(def.id)
    saveRun(cur)

    const lines = logMap[def.id] ?? []
    const per = Math.max(400, Math.floor(def.duration / Math.max(lines.length, 1)))

    // Kick off real side-effects for certain steps while logs stream.
    let sideEffect: Promise<unknown> | null = null
    if (def.id === "script") {
      sideEffect = writeScript(
        meta ?? {
          full,
          description: "A modern web application.",
          language: "TypeScript",
          stars: 0,
          topics: [],
          readmeExcerpt: "",
        },
        run.appUrl,
      ).then((t) => {
        scriptText = t
      })
    } else if (def.id === "voiceover") {
      sideEffect = synthesizeVoice(scriptText || "Devfields demo narration.")
    }

    for (const line of lines) {
      await sleep(per)
      const c = getRun(id)
      if (!c) return
      c.steps[i].logs.push(line)
      saveRun(c)
    }

    if (sideEffect) await sideEffect.catch(() => {})

    const done = getRun(id)
    if (!done) return
    done.steps[i].status = "done"
    done.steps[i].finishedAt = Date.now()
    saveRun(done)
  }

  // Build result + provenance assets
  const finalRun = getRun(id)
  if (!finalRun) return

  if (!scriptText) {
    scriptText = `Meet ${full.split("/")[1]} — an automated demo generated by Devfields.`
  }

  const bucket = process.env.B2_BUCKET || "devfields"
  const assetSpecs: { key: string; label: string; kind: Asset["kind"]; size: string; provider: Asset["provider"]; seed: string }[] = [
    { key: `runs/${id}/manifest.json`, label: "Provenance manifest", kind: "json", size: "3.1 KB", provider: "Backblaze B2", seed: full + id },
    { key: `runs/${id}/script.json`, label: "Narration script", kind: "text", size: "2.4 KB", provider: "GMI Cloud", seed: scriptText },
    { key: `runs/${id}/voiceover.mp3`, label: "Voiceover audio", kind: "audio", size: "1.2 MB", provider: "ElevenLabs", seed: "audio" + id },
    { key: `runs/${id}/frames.zip`, label: "Captured frames", kind: "image", size: "8.7 MB", provider: "Devfields", seed: "frames" + id },
    { key: `runs/${id}/demo.mp4`, label: "Final demo video", kind: "video", size: "24.3 MB", provider: "Devfields", seed: "video" + id },
  ]

  const assets: Asset[] = []
  for (const s of assetSpecs) {
    const { b2Key } = await uploadToB2(s.key, s.seed)
    const hash = await shortHash(s.seed)
    assets.push({
      key: s.key,
      label: s.label,
      kind: s.kind,
      size: s.size,
      b2Key,
      hash,
      provider: s.provider,
    })
  }

  finalRun.result = {
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    posterUrl: `/demo-poster.png`,
    durationSec: 178,
    title: `${full.split("/")[1]} — Demo`,
    summary: meta?.description ?? "An automated 3-minute demo of your deployed application.",
    scriptPreview: scriptText,
    assets,
  }
  finalRun.status = "done"
  saveRun(finalRun)
}
